module.exports = {
  'rules': {
    //best practices
    'default-case': 'error',
    'no-multi-spaces': 'error',
    'array-callback-return': 'error',
    'block-scoped-var': 'error',
    'consistent-return': 'error',
    'curly': 'error',
    'dot-location': ['error', 'property'],
    'eqeqeq': 'error',
    'guard-for-in': 'error',
    'no-caller': 'error',
    'no-eval': 'error',
    'no-implied-eval': 'error',
    'no-script-url': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-labels': 'error',
    'no-floating-decimal': 'error',
    'no-implicit-coercion': ['error', { 'allow': ['!!'] }],
    'no-implicit-globals': 'error',
    'no-invalid-this': 'error',
    'no-lone-blocks': 'error',
    'no-loop-func': 'error',
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-wrappers': 'error',
    'no-octal-escape': 'error',
    'no-proto': 'error',
    'no-return-assign': 'error',
    'no-self-compare': 'error',
    'no-sequences': 'error',
    'no-throw-literal': 'error',
    'prefer-promise-reject-errors': 'error',
    'no-unmodified-loop-condition': 'error',
    'no-unused-expressions': 'error',
    'no-useless-call': 'error',
    'no-useless-concat': 'error',
    'no-useless-return': 'error',
    'no-void': 'error',
    'no-with': 'error',
    'radix': 'error',
    'vars-on-top': 'error',
    'wrap-iife': 'error',
    'yoda': 'error',

    //variables
    'no-shadow': 'error',
    'no-shadow-restricted-names': 'error',
    'no-undef-init': 'error',
    'no-use-before-define': 'error',

    //style
    'brace-style': ['error', '1tbs'],
    'indent': ['error', 2, {
        'MemberExpression': 0,
        'SwitchCase': 1
    }],
    'semi': ['error', 'always'],
    'comma-dangle': ['error', 'never'],
    'keyword-spacing': 'error',
    'space-before-function-paren': ['error', {
        'anonymous': 'always',
        'named': 'never'
    }],
    'space-in-parens': 'error',
    'space-infix-ops': 'error',
    'space-unary-ops': 'error',
    'space-before-blocks': 'error',
    'array-bracket-spacing': 'error',
    'object-curly-spacing': ['error', 'always'],
    'block-spacing': 'error',
    'switch-colon-spacing': 'error',
    'camelcase': 'error',
    'comma-spacing': 'error',
    'comma-style': 'error',
    'computed-property-spacing': 'error',
    'consistent-this': ['error', 'me'],
    'func-call-spacing': 'error',
    'func-name-matching': 'error',
    'key-spacing': 'error',
    'max-depth': 'error',
    'max-len': ['error', 150],
    'max-params': 'error',
    'max-statements-per-line': 'error',
    'new-cap': 'error',
    'new-parens': 'error',
    'no-array-constructor': 'error',
    'no-new-object': 'error',
    'no-bitwise': 'error',
    'no-continue': 'error',
    'no-mixed-operators': 'error',
    'no-multi-assign': 'error',
    'no-multiple-empty-lines': 'error',
    'no-nested-ternary': 'error',
    'no-trailing-spaces': ['error', { 'skipBlankLines': true }],
    'no-underscore-dangle': 'error',
    'no-unneeded-ternary': 'error',
    'no-whitespace-before-property': 'error',
    'padded-blocks': ['error', 'never'],
    'quote-props': ['error', 'consistent-as-needed', { 'keywords': true }],
    'quotes': ['error', 'single', { 'avoidEscape': true }],
    'jsx-quotes': ['error', 'prefer-single'],
    'semi-spacing': 'error',
    'semi-style': ['error', 'last'],
    'func-style': ['error', 'declaration']
  }
};
